trigger:
  - develop

pool:
    name: 'demo-pool'

stages:
  - stage: BuildApp
    jobs:
      - job: Build
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'Hello world'