trigger:
  - develop

pool:
    vmImage: 'ubuntu-latest'

stages:
  - stage: Build the Application
    jobs:
      - job: Build
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'Hello world'